# Generated by Django 4.2.1 on 2026-06-15 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTranslationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(choices=[('text', 'Text Translator'), ('file', 'File Translator'), ('voice', 'Voice Translator')], max_length=20)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('source_lang', models.CharField(max_length=50)),
                ('target_lang', models.CharField(max_length=50)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
