# Generated by Django 6.0.4 on 2026-06-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_pricingplan_usersubscription_paymenttransaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymenttransaction",
            old_name="merchant_transaction_id",
            new_name="merchant_order_id",
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="merchant_transaction_id",
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="payment_id",
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="phonepe_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="payment_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="app.paymenttransaction",
            ),
        ),
    ]
