# Generated by Django 4.2.1 on 2026-06-24 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_merchant_transaction_id_paymenttransaction_merchant_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='plan_order',
            field=models.PositiveIntegerField(default=1, help_text='Priority level (e.g. 1=Basic, 2=Pro, 3=Business)'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_upgrade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='previous_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgraded_from_subscriptions', to='app.pricingplan'),
        ),
    ]
