# Generated by Django 5.0.14 on 2026-08-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_usertranslationhistory_tool_type_pageviewlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_notification_sent',
            field=models.BooleanField(default=False, help_text='Designates whether email notification has been sent to registered users.'),
        ),
    ]
