# Generated by Django 5.0.14 on 2026-08-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_blog_is_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttranslationhistory',
            name='transliterated_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertranslationhistory',
            name='transliterated_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
