# Generated by Django 5.0.14 on 2026-08-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_documenttranslationhistory_transliterated_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIClassEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('enrolled', 'Enrolled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'AI Class Enquiry',
                'verbose_name_plural': 'AI Class Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
