# Generated by Django 5.0.14 on 2026-08-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_aiclassenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='send_email_notification',
            field=models.BooleanField(default=True, help_text='Designates whether email notification should be sent to registered users upon publishing.'),
        ),
    ]
