# Generated by Django 5.0.14 on 2026-09-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_blog_send_email_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='scheduled_publish_date',
            field=models.DateTimeField(blank=True, help_text='Set a future date and time to schedule automatic publishing.', null=True),
        ),
    ]
