# Reusable 200+ languages list for Teltam.ai translation workspace tools.
# Maps ISO-639 language codes to their English names.

LANGUAGES = [
    {"code": "af", "name": "Afrikaans"},
    {"code": "ak", "name": "Akan"},
    {"code": "sq", "name": "Albanian"},
    {"code": "am", "name": "Amharic"},
    {"code": "ar", "name": "Arabic"},
    {"code": "hy", "name": "Armenian"},
    {"code": "as", "name": "Assamese"},
    {"code": "ay", "name": "Aymara"},
    {"code": "az", "name": "Azerbaijani"},
    {"code": "bm", "name": "Bambara"},
    {"code": "eu", "name": "Basque"},
    {"code": "be", "name": "Belarusian"},
    {"code": "bn", "name": "Bengali"},
    {"code": "bho", "name": "Bhojpuri"},
    {"code": "bs", "name": "Bosnian"},
    {"code": "br", "name": "Breton"},
    {"code": "bg", "name": "Bulgarian"},
    {"code": "my", "name": "Burmese (Myanmar)"},
    {"code": "ca", "name": "Catalan"},
    {"code": "ceb", "name": "Cebuano"},
    {"code": "ny", "name": "Chichewa"},
    {"code": "zh-CN", "name": "Chinese (Simplified)"},
    {"code": "zh-TW", "name": "Chinese (Traditional)"},
    {"code": "co", "name": "Corsican"},
    {"code": "hr", "name": "Croatian"},
    {"code": "cs", "name": "Czech"},
    {"code": "da", "name": "Danish"},
    {"code": "dv", "name": "Dhivehi"},
    {"code": "doi", "name": "Dogri"},
    {"code": "nl", "name": "Dutch"},
    {"code": "dz", "name": "Dzongkha"},
    {"code": "en", "name": "English"},
    {"code": "eo", "name": "Esperanto"},
    {"code": "et", "name": "Estonian"},
    {"code": "ee", "name": "Ewe"},
    {"code": "fo", "name": "Faroese"},
    {"code": "fj", "name": "Fijian"},
    {"code": "tl", "name": "Filipino (Tagalog)"},
    {"code": "fi", "name": "Finnish"},
    {"code": "fr", "name": "French"},
    {"code": "fy", "name": "Frisian"},
    {"code": "gl", "name": "Galician"},
    {"code": "ka", "name": "Georgian"},
    {"code": "de", "name": "German"},
    {"code": "el", "name": "Greek"},
    {"code": "kl", "name": "Greenlandic"},
    {"code": "gn", "name": "Guarani"},
    {"code": "gu", "name": "Gujarati"},
    {"code": "ht", "name": "Haitian Creole"},
    {"code": "ha", "name": "Hausa"},
    {"code": "haw", "name": "Hawaiian"},
    {"code": "iw", "name": "Hebrew"},
    {"code": "hi", "name": "Hindi"},
    {"code": "hmn", "name": "Hmong"},
    {"code": "hu", "name": "Hungarian"},
    {"code": "is", "name": "Icelandic"},
    {"code": "ig", "name": "Igbo"},
    {"code": "ilo", "name": "Ilocano"},
    {"code": "id", "name": "Indonesian"},
    {"code": "ga", "name": "Irish"},
    {"code": "it", "name": "Italian"},
    {"code": "ja", "name": "Japanese"},
    {"code": "jw", "name": "Javanese"},
    {"code": "kn", "name": "Kannada"},
    {"code": "kk", "name": "Kazakh"},
    {"code": "km", "name": "Khmer"},
    {"code": "rw", "name": "Kinyarwanda"},
    {"code": "gom", "name": "Konkani"},
    {"code": "ko", "name": "Korean"},
    {"code": "kri", "name": "Krio"},
    {"code": "ku", "name": "Kurdish (Kurmanji)"},
    {"code": "ckb", "name": "Kurdish (Sorani)"},
    {"code": "ky", "name": "Kyrgyz"},
    {"code": "lo", "name": "Lao"},
    {"code": "la", "name": "Latin"},
    {"code": "lv", "name": "Latvian"},
    {"code": "ln", "name": "Lingala"},
    {"code": "lt", "name": "Lithuanian"},
    {"code": "lg", "name": "Luganda"},
    {"code": "lb", "name": "Luxembourgish"},
    {"code": "mk", "name": "Macedonian"},
    {"code": "mai", "name": "Maithili"},
    {"code": "mg", "name": "Malagasy"},
    {"code": "ms", "name": "Malay"},
    {"code": "ml", "name": "Malayalam"},
    {"code": "mt", "name": "Maltese"},
    {"code": "mi", "name": "Maori"},
    {"code": "mr", "name": "Marathi"},
    {"code": "mni-Mtei", "name": "Meiteilon (Manipuri)"},
    {"code": "lus", "name": "Mizo"},
    {"code": "mn", "name": "Mongolian"},
    {"code": "ne", "name": "Nepali"},
    {"code": "no", "name": "Norwegian"},
    {"code": "or", "name": "Odia (Oriya)"},
    {"code": "om", "name": "Oromo"},
    {"code": "ps", "name": "Pashto"},
    {"code": "fa", "name": "Persian"},
    {"code": "pl", "name": "Polish"},
    {"code": "pt", "name": "Portuguese"},
    {"code": "pa", "name": "Punjabi"},
    {"code": "qu", "name": "Quechua"},
    {"code": "ro", "name": "Romanian"},
    {"code": "ru", "name": "Russian"},
    {"code": "sm", "name": "Samoan"},
    {"code": "sa", "name": "Sanskrit"},
    {"code": "gd", "name": "Scots Gaelic"},
    {"code": "nso", "name": "Sepedi"},
    {"code": "sr", "name": "Serbian"},
    {"code": "st", "name": "Sesotho"},
    {"code": "sn", "name": "Shona"},
    {"code": "sd", "name": "Sindhi"},
    {"code": "si", "name": "Sinhala"},
    {"code": "sk", "name": "Slovak"},
    {"code": "sl", "name": "Slovenian"},
    {"code": "so", "name": "Somali"},
    {"code": "es", "name": "Spanish"},
    {"code": "su", "name": "Sundanese"},
    {"code": "sw", "name": "Swahili"},
    {"code": "sv", "name": "Swedish"},
    {"code": "tg", "name": "Tajik"},
    {"code": "ta", "name": "Tamil"},
    {"code": "tt", "name": "Tatar"},
    {"code": "te", "name": "Telugu"},
    {"code": "th", "name": "Thai"},
    {"code": "ti", "name": "Tigrinya"},
    {"code": "ts", "name": "Tsonga"},
    {"code": "tr", "name": "Turkish"},
    {"code": "tk", "name": "Turkmen"},
    {"code": "ak", "name": "Twi"},
    {"code": "uk", "name": "Ukrainian"},
    {"code": "ur", "name": "Urdu"},
    {"code": "ug", "name": "Uyghur"},
    {"code": "uz", "name": "Uzbek"},
    {"code": "vi", "name": "Vietnamese"},
    {"code": "cy", "name": "Welsh"},
    {"code": "xh", "name": "Xhosa"},
    {"code": "yi", "name": "Yiddish"},
    {"code": "yo", "name": "Yoruba"},
    {"code": "zu", "name": "Zulu"},
    
    # Extra 70+ languages to reach 200+
    {"code": "ab", "name": "Abkhazian"},
    {"code": "aa", "name": "Afar"},
    {"code": "an", "name": "Aragonese"},
    {"code": "av", "name": "Avaric"},
    {"code": "ae", "name": "Avestan"},
    {"code": "ba", "name": "Bashkir"},
    {"code": "bi", "name": "Bislama"},
    {"code": "ch", "name": "Chamorro"},
    {"code": "ce", "name": "Chechen"},
    {"code": "cv", "name": "Chuvash"},
    {"code": "cr", "name": "Cree"},
    {"code": "cu", "name": "Church Slavic"},
    {"code": "fl", "name": "Flemish"},
    {"code": "fo", "name": "Faroese"},
    {"code": "ff", "name": "Fulah"},
    {"code": "hz", "name": "Herero"},
    {"code": "ho", "name": "Hiri Motu"},
    {"code": "iu", "name": "Inuktitut"},
    {"code": "ik", "name": "Inupiaq"},
    {"code": "jv", "name": "Javanese"},
    {"code": "kl", "name": "Kalaallisut"},
    {"code": "kr", "name": "Kanuri"},
    {"code": "ks", "name": "Kashmiri"},
    {"code": "ki", "name": "Kikuyu"},
    {"code": "kj", "name": "Kuanyama"},
    {"code": "kv", "name": "Komi"},
    {"code": "kg", "name": "Kongo"},
    {"code": "lu", "name": "Luba-Katanga"},
    {"code": "mh", "name": "Marshallese"},
    {"code": "gv", "name": "Manx"},
    {"code": "na", "name": "Nauru"},
    {"code": "nd", "name": "Northern Ndebele"},
    {"code": "nr", "name": "Southern Ndebele"},
    {"code": "ng", "name": "Ndonga"},
    {"code": "ii", "name": "Sichuan Yi"},
    {"code": "oc", "name": "Occitan"},
    {"code": "oj", "name": "Ojibwa"},
    {"code": "pi", "name": "Pali"},
    {"code": "sc", "name": "Sardinian"},
    {"code": "se", "name": "Northern Sami"},
    {"code": "sg", "name": "Sango"},
    {"code": "sr-Latn", "name": "Serbian (Latin)"},
    {"code": "st", "name": "Southern Sotho"},
    {"code": "ss", "name": "Swati"},
    {"code": "to", "name": "Tongan"},
    {"code": "tn", "name": "Tswana"},
    {"code": "ty", "name": "Tahitian"},
    {"code": "tw", "name": "Twi"},
    {"code": "ve", "name": "Venda"},
    {"code": "vo", "name": "Volapuk"},
    {"code": "wa", "name": "Walloon"},
    {"code": "wo", "name": "Wolof"},
    {"code": "za", "name": "Zhuang"},
    {"code": "ast", "name": "Asturian"},
    {"code": "brx", "name": "Bodo"},
    {"code": "car", "name": "Carib"},
    {"code": "chr", "name": "Cherokee"},
    {"code": "cop", "name": "Coptic"},
    {"code": "fur", "name": "Friulian"},
    {"code": "ia", "name": "Interlingua"},
    {"code": "jbo", "name": "Lojban"},
    {"code": "lad", "name": "Ladino"},
    {"code": "nap", "name": "Neapolitan"},
    {"code": "nog", "name": "Nogai"},
    {"code": "pap", "name": "Papiamento"},
    {"code": "pms", "name": "Piedmontese"},
    {"code": "syc", "name": "Classical Syriac"},
    {"code": "tpi", "name": "Tok Pisin"},
    {"code": "yua", "name": "Yucatec Maya"},
    {"code": "zap", "name": "Zapotec"}
]
