# Generated by Django 5.2.3 on 2025-06-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="videocategory",
            name="slug",
        ),
    ]
