# Generated by Django 5.2.3 on 2025-06-19 08:40

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_dashboard",
            "0003_blogpost_comment_show_status_alter_blogpost_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
    ]
