# Generated by Django 4.2 on 2025-06-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0005_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="cta_link",
        ),
        migrations.RemoveField(
            model_name="video",
            name="cta_text",
        ),
    ]
