# Generated by Django 4.2 on 2025-06-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0006_remove_video_cta_link_remove_video_cta_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="video_id",
        ),
    ]
