# Generated by Django 4.2 on 2025-06-25 12:10

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0007_remove_video_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
    ]
