# Generated by Django 4.2 on 2025-07-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0008_alter_video_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
