# Generated by Django 5.0.7 on 2025-05-17 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "register_as",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("company", "Company / Organization"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("education", "Education"),
                            ("media", "Media & Entertainment"),
                            ("legal", "Legal"),
                            ("healthcare", "Healthcare"),
                            ("ecommerce", "E-commerce"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "find_us",
                    models.CharField(
                        choices=[
                            ("google", "Google Search"),
                            ("social", "Social Media"),
                            ("referral", "Referral"),
                            ("ads", "Online Advertisement"),
                            ("events", "Events / Webinars"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Translation"),
                            ("business", "Business Use"),
                            ("content", "Content Creation"),
                            ("academic", "Academic / Research"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("languages", models.JSONField()),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("1-10", "1-10 Images"),
                            ("11-50", "11-50 Images"),
                            ("51-100", "51-100 Images"),
                            ("100+", "100+ Images"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Details",
                "verbose_name_plural": "Survey Details",
            },
        ),
        migrations.CreateModel(
            name="Translations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("language", models.CharField(max_length=100, null=True)),
                ("target_language", models.CharField(max_length=100, null=True)),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation Details",
                "verbose_name_plural": "Translation Details",
            },
        ),
        migrations.CreateModel(
            name="Output_files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="outputs/")),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.translations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Final ",
            },
        ),
        migrations.CreateModel(
            name="User_OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp", models.CharField(max_length=6)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("review_text", models.TextField()),
                ("star_rating", models.IntegerField(null=True)),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reviews",
                "verbose_name_plural": "Reviews",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=15, unique=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Self Details",
                "verbose_name_plural": "User Self Details",
            },
        ),
    ]
