# Generated by Django 4.2 on 2025-07-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="translations",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user_reviews",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
