# Generated by Django 4.2 on 2025-07-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_surveyresponse_is_seen_translations_is_seen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="output_files",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
