# Generated by Django 5.0.7 on 2025-05-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_user_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="translations",
            name="target_language",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
