# Generated by Django 5.0.7 on 2025-05-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_user_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_reviews",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
