# Generated by Django 4.2 on 2025-07-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_newsletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
    ]
