# Generated by Django 5.0.7 on 2025-05-07 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_user_reviews_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "register_as",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("company", "Company / Organization"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("education", "Education"),
                            ("media", "Media & Entertainment"),
                            ("legal", "Legal"),
                            ("healthcare", "Healthcare"),
                            ("ecommerce", "E-commerce"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "find_us",
                    models.CharField(
                        choices=[
                            ("google", "Google Search"),
                            ("social", "Social Media"),
                            ("referral", "Referral"),
                            ("ads", "Online Advertisement"),
                            ("events", "Events / Webinars"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Translation"),
                            ("business", "Business Use"),
                            ("content", "Content Creation"),
                            ("academic", "Academic / Research"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("languages", models.JSONField()),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("1-10", "1-10 Images"),
                            ("11-50", "11-50 Images"),
                            ("51-100", "51-100 Images"),
                            ("100+", "100+ Images"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
