# Generated by Django 4.2 on 2026-04-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='max_image_requests',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_pdf_uploads',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_translations',
        ),
    ]
