# Generated by Django 4.2 on 2026-04-17 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_plan_max_image_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.transaction'),
            preserve_default=False,
        ),
    ]
