# Generated by Django 4.2 on 2026-04-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_subscription_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.IntegerField(default=30),
        ),
    ]
